== ansible-envase

Quick role that installs and configures a single node OpenShift installation (a la `oc cluster up`) to a cloud provider and starts it up.

=== Requirements

The role uses the EC2 module so Boto is required.

=== Role Variables

A description of the settable variables for this role should go here, including any variables that are in defaults/main.yml, vars/main.yml, and any variables that can/should be set via parameters to the role. Any variables that are read from other roles and/or the global scope (ie. hostvars, group vars, etc.) should be mentioned here as well.

=== Dependencies

A list of other roles hosted on Galaxy should go here, plus any details in regards to parameters that may need to be set for other roles, or variables that are used from other roles.

=== Example Playbook

Including an example of how to use your role (for instance, with variables passed in as parameters) is always nice for users too:

    - hosts: servers
      roles:
         - { role: username.rolename, x: 42 }

=== License

Apache 2.0

=== Author Information

Dan Hawker

=== What Happens

* Creates EC2 instance in AWS, using flavour and AMI defined
* Downloads, installs and configures `oc` client tools (https://github.com/openshift/origin)
* Downloads, installs and configures `oc-cluster` helper (https://github.com/openshift-evangelists/oc-cluster-wrapper/)
* Starts cluster using `oc-cluster` - setting `--public-hostname` and `--routing-suffix` accordingly so that AWS stuff works.
